import type { DetectionPlugin, DetectionRequest, DetectionResult } from '../plugin.js'

/**
 * Built-in heuristic adapter — no API key required.
 * Uses phrase matching against common AI writing patterns.
 * Useful for development and as a fallback.
 */

const AI_SIGNALS: string[] = [
  // Self-identification
  'as an ai',
  "i'm an ai",
  'i am an ai',
  'language model',
  'large language model',
  'i was trained',
  'my training data',
  'my knowledge cutoff',
  "i don't have access to real-time",
  // Refusals
  'i cannot provide',
  'i am not able to',
  'i cannot assist with',
  'i apologize, but i',
  // Sycophantic openers
  "i'd be happy to",
  "i'd be glad to",
  'certainly!',
  'absolutely!',
  'of course!',
  'great question',
  'as a helpful assistant',
  // AI prose tells
  'dive deeper into',
  'delve into',
  "it's worth noting",
  'it is worth noting',
  'in conclusion,',
  'to summarize,',
  'in summary,',
  'furthermore,',
  'moreover,',
  'on the other hand,',
  'it is important to note',
  'it should be noted',
  'this comprehensive',
  'a comprehensive',
  // AI digest / newsletter tells
  'key takeaways',
  'key highlights',
  'quick summary',
  'tl;dr',
  'tldr',
  'what you need to know',
  'here\'s what happened',
  'here\'s a summary',
  'weekly digest',
  'daily digest',
  'curated by ai',
  'generated by ai',
  'powered by ai',
  'written by ai',
]

// Regex-based structural signals — markdown formatting in emails is a strong AI tell
const AI_PATTERNS: RegExp[] = [
  /\*\*[^*]{3,}\*\*/,           // **bold text** — AI outputting markdown in email
  /#{1,3} [A-Z]/,               // ## Heading — markdown headers in email
  /^\s*[-•]\s+\w/m,             // bullet list items
  /^\s*\d+\.\s+\w/m,            // numbered list items
  /\*[^*]{3,}\*/,               // *italic* — markdown italics
  /`[^`]+`/,                    // `inline code` in email
  /📌|📊|📈|🔑|✅|⚡|💡|🎯|🚀|👉/, // heavy emoji usage common in AI newsletters
]

export class StubDetectionAdapter implements DetectionPlugin {
  readonly name = 'stub'
  readonly version = '1.0.0'

  private threshold = 0.4

  configure(config: Record<string, string>): void {
    if (config.threshold !== undefined) {
      this.threshold = parseFloat(config.threshold)
    }
  }

  isConfigured(): boolean {
    return true
  }

  async detect(request: DetectionRequest): Promise<DetectionResult> {
    const lower = request.text.toLowerCase()
    const wordCount = request.text.split(/\s+/).filter(Boolean).length

    // Phrase signals
    let phraseMatches = 0
    for (const signal of AI_SIGNALS) {
      if (lower.includes(signal)) phraseMatches++
    }

    // Structural / regex signals — each match worth more weight
    let patternMatches = 0
    for (const pattern of AI_PATTERNS) {
      if (pattern.test(request.text)) patternMatches++
    }

    // Structural signals weighted 2x — markdown in email is highly diagnostic
    const rawScore = Math.min((phraseMatches * 0.2) + (patternMatches * 0.35), 1.0)

    // Penalise very short snippets — not enough signal
    const lengthPenalty = wordCount < 15 ? 0.6 : 1.0
    const confidence = parseFloat((rawScore * lengthPenalty).toFixed(2))

    return {
      isAI: confidence >= this.threshold,
      confidence,
      provider: 'stub',
    }
  }
}
