import type { DetectionPlugin, DetectionRequest, DetectionResult } from '../plugin.js'

/**
 * Built-in heuristic adapter — no API key, no network, fully on-device.
 *
 * Scoring combines four independent signals:
 *   1. Phrase signals    — AI lexicon / boilerplate phrases
 *   2. Structural signals — markdown formatting in plain-text email
 *   3. Statistical signals — sentence-length uniformity, transition density,
 *                           paragraph uniformity, list density
 *   4. Length guard      — very short text gets a confidence penalty
 */

// ── 1. Phrase signals ──────────────────────────────────────────────────────────

const AI_PHRASES: string[] = [
  // Self-identification
  'as an ai', "i'm an ai", 'i am an ai', 'language model',
  'large language model', 'i was trained', 'my training data',
  'my knowledge cutoff', "i don't have access to real-time",
  // Sycophantic openers
  "i'd be happy to", "i'd be glad to", 'certainly!', 'absolutely!',
  'of course!', 'great question', 'as a helpful assistant',
  // AI prose tells
  'dive deeper into', 'delve into', "it's worth noting",
  'it is worth noting', 'in conclusion,', 'to summarize,',
  'in summary,', 'furthermore,', 'moreover,', 'on the other hand,',
  'it is important to note', 'it should be noted',
  'this comprehensive', 'a comprehensive overview',
  // Digest / newsletter tells
  'key takeaways', 'key highlights', 'quick summary',
  "tl;dr", 'tldr', 'what you need to know', "here's what happened",
  "here's a summary", 'weekly digest', 'daily digest',
  'curated by ai', 'generated by ai', 'powered by ai', 'written by ai',
  // Business-speak AI loves
  'actionable insights', 'moving forward', 'going forward',
  "in today's fast-paced", "in today's dynamic", "in today's edition",
  'as we navigate', 'in the ever-evolving', 'paradigm shift',
  // Email-specific AI closings
  "please don't hesitate to reach out", 'please feel free to reach out',
  'looking forward to connecting', 'i hope this email finds you',
  'i hope this message finds you',
  'thank you for your time and consideration',
  // AI newsletter openers
  "today's highlights", "in this week's", 'welcome to another edition',
  "this week's top stories",
  // Overused transitions
  'first and foremost', 'last but not least',
  'it goes without saying', 'needless to say',
  'at the end of the day',
]

// ── 2. Structural / regex signals ─────────────────────────────────────────────

interface StructuralSignal {
  pattern: RegExp
  weight: number
}

const STRUCTURAL_SIGNALS: StructuralSignal[] = [
  { pattern: /\*\*[^*]{3,}\*\*/,         weight: 0.40 }, // **bold** in email
  { pattern: /#{1,3} [A-Z]/,              weight: 0.40 }, // ## Heading
  { pattern: /^\s*[-•]\s+\w/m,            weight: 0.25 }, // bullet list
  { pattern: /^\s*\d+\.\s+\w/m,           weight: 0.25 }, // numbered list
  { pattern: /\*[^*]{3,}\*/,              weight: 0.20 }, // *italic*
  { pattern: /`[^`]+`/,                   weight: 0.15 }, // `code`
  { pattern: /\[.{3,50}\]\(https?:\/\//,  weight: 0.20 }, // [text](url)
  { pattern: /^[-=]{4,}\s*$/m,            weight: 0.30 }, // --- divider
  { pattern: /📌|📊|📈|🔑|✅|⚡|💡|🎯|🚀|👉/, weight: 0.20 }, // heavy emoji
]

// ── 3. Statistical helpers ─────────────────────────────────────────────────────

function extractSentences(text: string): string[] {
  return text
    .split(/(?<=[.!?])\s+/)
    .map(s => s.trim())
    .filter(s => s.split(/\s+/).length >= 4)
}

/**
 * Coefficient of variation of sentence word-counts.
 * AI tends to write uniformly-sized sentences (low CV → score near 1).
 * Humans vary more (high CV → score near 0).
 */
function sentenceUniformityScore(sentences: string[]): number {
  if (sentences.length < 4) return 0
  const lengths = sentences.map(s => s.split(/\s+/).filter(Boolean).length)
  const mean = lengths.reduce((a, b) => a + b, 0) / lengths.length
  if (mean < 4) return 0
  const variance = lengths.reduce((a, b) => a + (b - mean) ** 2, 0) / lengths.length
  const cv = Math.sqrt(variance) / mean
  // CV < 0.25 → very uniform; CV > 0.55 → varied human
  return parseFloat(Math.max(0, 1 - cv / 0.4).toFixed(3))
}

const TRANSITION_WORDS = [
  'however', 'furthermore', 'moreover', 'additionally', 'consequently',
  'therefore', 'thus', 'hence', 'nevertheless', 'nonetheless', 'meanwhile',
  'subsequently', 'in addition', 'as a result', 'in contrast', 'in particular',
  'specifically', 'notably', 'importantly', 'significantly', 'ultimately',
  'essentially', 'interestingly', 'surprisingly', 'evidently',
]

/**
 * Transition-word density per sentence.
 * AI writing is rich in connective tissue; humans are more terse/casual.
 */
function transitionDensityScore(text: string, sentences: string[]): number {
  if (sentences.length === 0) return 0
  const lower = text.toLowerCase()
  const hits = TRANSITION_WORDS.filter(t => lower.includes(t)).length
  const density = hits / sentences.length
  // > 0.4 transitions/sentence is very AI-like
  return parseFloat(Math.min(1, density / 0.4).toFixed(3))
}

/**
 * Paragraph length uniformity.
 * AI-generated digests tend to have consistent paragraph sizes.
 */
function paragraphUniformityScore(text: string): number {
  const paragraphs = text
    .split(/\n\n+/)
    .map(p => p.trim())
    .filter(p => p.split(/\s+/).length >= 10)
  if (paragraphs.length < 3) return 0
  const lengths = paragraphs.map(p => p.split(/\s+/).filter(Boolean).length)
  const mean = lengths.reduce((a, b) => a + b, 0) / lengths.length
  if (mean < 10) return 0
  const variance = lengths.reduce((a, b) => a + (b - mean) ** 2, 0) / lengths.length
  const cv = Math.sqrt(variance) / mean
  return parseFloat(Math.max(0, 1 - cv / 0.5).toFixed(3))
}

/**
 * Fraction of lines that are list items.
 * AI loves to enumerate; > 25% of lines as bullets is a strong signal.
 */
function listDensityScore(text: string): number {
  const lines = text.split('\n').filter(l => l.trim().length > 0)
  if (lines.length < 3) return 0
  const listLines = lines.filter(
    l => /^\s*[-•*]\s+\w/.test(l) || /^\s*\d+\.\s+\w/.test(l),
  )
  return parseFloat(Math.min(1, (listLines.length / lines.length) / 0.25).toFixed(3))
}

// ── Adapter ────────────────────────────────────────────────────────────────────

export class StubDetectionAdapter implements DetectionPlugin {
  readonly name = 'stub'
  readonly version = '2.0.0'

  private threshold = 0.4

  configure(config: Record<string, string>): void {
    if (config.threshold !== undefined) {
      this.threshold = parseFloat(config.threshold)
    }
  }

  isConfigured(): boolean {
    return true
  }

  async detect(request: DetectionRequest): Promise<DetectionResult> {
    const text = request.text
    const lower = text.toLowerCase()
    const words = text.split(/\s+/).filter(Boolean)
    const wordCount = words.length
    const sentences = extractSentences(text)

    // --- Phrase signal (each match +0.18, capped at 0.72) ---
    const phraseHits = AI_PHRASES.filter(p => lower.includes(p)).length
    const phraseScore = Math.min(phraseHits * 0.18, 0.72)

    // --- Structural signal (weighted sum, capped at 0.80) ---
    let structScore = 0
    for (const { pattern, weight } of STRUCTURAL_SIGNALS) {
      if (pattern.test(text)) structScore += weight
    }
    structScore = Math.min(structScore, 0.80)

    // --- Statistical signals ---
    const uniformity  = sentenceUniformityScore(sentences)
    const transitions = transitionDensityScore(text, sentences)
    const paragraphs  = paragraphUniformityScore(text)
    const lists       = listDensityScore(text)

    // Weighted combination: structural/phrase are strongest signals;
    // statistical signals are supporting evidence
    const raw =
      phraseScore    * 0.30 +
      structScore    * 0.35 +
      uniformity     * 0.15 +
      transitions    * 0.10 +
      paragraphs     * 0.05 +
      lists          * 0.05

    // Length penalty: very short snippets lack enough signal
    const lengthFactor = wordCount < 10 ? 0.4 : wordCount < 25 ? 0.7 : 1.0
    const confidence = parseFloat(Math.min(raw * lengthFactor, 1.0).toFixed(2))

    return {
      isAI: confidence >= this.threshold,
      confidence,
      provider: 'stub',
    }
  }
}
